hassanhabib/OtripleS

OtripleS.Web.Api/Brokers/Storage/IStorageBroker.cs
OtripleS.Web.Api/Brokers/Storage/StorageBroker.Students.cs
OtripleS.Web.Api/Brokers/Storage/StorageBroker.cs

* SelectAllStudents IQueryable for StorageBroker

StorageBroker SelectAllStudents

---

OtripleS.Web.Api/Brokers/Storage/IStorageBroker.cs
OtripleS.Web.Api/Brokers/Storage/StorageBroker.Students.cs

Method on StorageBroker.student.cs to fetch students by unique identifier

Added GetStudent(Guid) method to StorageBroker

---

OtripleS.Web.Api.Tests.Unit/Services/StudentServiceTests/StudentServiceTests.cs
OtripleS.Web.Api/Services/StudentService.Validations.cs
OtripleS.Web.Api/Services/StudentService.cs

I added validation on student service DeleteStudentAsync(Guid studentId)

Feature Added validation for student to studentservice DeleteStudentAsync(Guid studentId)

---

OtripleS.Web.Api.Tests.Unit/Services/StudentServiceTests/StudentServiceTests.Exceptions.Retrieve.cs
OtripleS.Web.Api.Tests.Unit/Services/StudentServiceTests/StudentServiceTests.Logic.cs
OtripleS.Web.Api.Tests.Unit/Services/StudentServiceTests/StudentServiceTests.Validations.Retrieve.cs
OtripleS.Web.Api.Tests.Unit/Services/StudentServiceTests/StudentServiceTests.cs
OtripleS.Web.Api/Controllers/StudentsController.cs
OtripleS.Web.Api/Services/IStudentService.cs
OtripleS.Web.Api/Services/StudentService.Exceptions.cs
OtripleS.Web.Api/Services/StudentService.Validations.cs
OtripleS.Web.Api/Services/StudentService.cs

- Service change
- Validations for warning
- Exceptions

RetrieveAll Students

---

OtripleS.Web.Api.Tests.Unit/Services/TeacherServiceTests/TeacherServiceTests.Exceptions.Delete.cs
OtripleS.Web.Api.Tests.Unit/Services/TeacherServiceTests/TeacherServiceTests.Logic.cs
OtripleS.Web.Api.Tests.Unit/Services/TeacherServiceTests/TeacherServiceTests.Validations.Delete.cs
OtripleS.Web.Api.Tests.Unit/Services/TeacherServiceTests/TeacherServiceTests.cs
OtripleS.Web.Api/Models/Teachers/Exceptions/InvalidTeacherInputException.cs
OtripleS.Web.Api/Models/Teachers/Exceptions/LockedTeacherException.cs
OtripleS.Web.Api/Models/Teachers/Exceptions/NotFoundTeacherException.cs
OtripleS.Web.Api/Models/Teachers/Exceptions/TeacherDependencyException.cs
OtripleS.Web.Api/Models/Teachers/Exceptions/TeacherServiceException.cs
OtripleS.Web.Api/Models/Teachers/Exceptions/TeacherValidationException.cs
OtripleS.Web.Api/Services/Teachers/ITeacherService.cs
OtripleS.Web.Api/Services/Teachers/TeacherService.Exceptions.cs
OtripleS.Web.Api/Services/Teachers/TeacherService.Validations.cs
OtripleS.Web.Api/Services/Teachers/TeacherService.cs
OtripleS.Web.Api/Startup.cs

- Service - Delete
- Validations
- Exceptions

Teacher Service Delete by Id

---

OtripleS.Web.Api.Tests.Acceptance/APIs/Students/StudentsApiTests.Logic.cs
OtripleS.Web.Api.Tests.Acceptance/APIs/Students/StudentsApiTests.cs
OtripleS.Web.Api.Tests.Acceptance/Brokers/OtripleSApiBroker.Students.cs

GetAll Students acceptance tests

Acceptance Test - GetAllStudents

---

OtripleS.Web.Api.Tests.Unit/Services/TeacherServiceTests/TeacherServiceTests.Exceptions.Modify.cs
OtripleS.Web.Api.Tests.Unit/Services/TeacherServiceTests/TeacherServiceTests.Logic.cs
OtripleS.Web.Api.Tests.Unit/Services/TeacherServiceTests/TeacherServiceTests.Validations.Modify.cs
OtripleS.Web.Api/Services/Teachers/ITeacherService.cs
OtripleS.Web.Api/Services/Teachers/TeacherService.Validations.cs
OtripleS.Web.Api/Services/Teachers/TeacherService.cs

- Service
- Validations with tests
- Exceptions with tests

Teacher Service Modify

---

OtripleS.Web.Api/Controllers/TeachersController.cs

#1 Implemented teacher modification endpoint.
#2 Implemented get all teachers endpoint.

Teacher modification endpoint

---

OtripleS.Web.Api/Brokers/Storage/StorageBroker.Classroom.cs
OtripleS.Web.Api/Migrations/20200720164344_AddClassroom.Designer.cs
OtripleS.Web.Api/Migrations/20200720164344_AddClassroom.cs
OtripleS.Web.Api/Models/Classrooms/Classroom.cs
OtripleS.Web.Api/Models/Classrooms/ClassroomStatus.cs

Adding Classroom model

---

OtripleS.Web.Api.Tests.Unit/Services/ClassroomServiceTests/ClassroomServiceTests.Exceptions.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/ClassroomServiceTests/ClassroomServiceTests.Logic.cs
OtripleS.Web.Api.Tests.Unit/Services/ClassroomServiceTests/ClassroomServiceTests.Validations.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/ClassroomServiceTests/ClassroomServiceTests.cs
OtripleS.Web.Api/Brokers/Storage/IStorageBroker.Classrooms.cs
OtripleS.Web.Api/Models/Classrooms/Exceptions/AlreadyExistsClassroomException.cs
OtripleS.Web.Api/Models/Classrooms/Exceptions/ClassroomDependencyException.cs
OtripleS.Web.Api/Models/Classrooms/Exceptions/ClassroomServiceException.cs
OtripleS.Web.Api/Models/Classrooms/Exceptions/ClassroomValidationException.cs
OtripleS.Web.Api/Models/Classrooms/Exceptions/InvalidClassroomException.cs
OtripleS.Web.Api/Models/Classrooms/Exceptions/NullClassroomException.cs
OtripleS.Web.Api/Services/Classrooms/ClassroomService.Exceptions.cs
OtripleS.Web.Api/Services/Classrooms/ClassroomService.Validations.cs
OtripleS.Web.Api/Services/Classrooms/ClassroomService.cs
OtripleS.Web.Api/Services/Classrooms/IClassroomService.cs
OtripleS.Web.Api/Startup.cs

- Service
- Validations
- Exceptions

Classroom Service Add

---

OtripleS.Web.Api.Tests.Unit/Services/ClassroomServiceTests/ClassroomServiceTests.Exceptions.Delete.cs
OtripleS.Web.Api.Tests.Unit/Services/ClassroomServiceTests/ClassroomServiceTests.Logic.cs
OtripleS.Web.Api.Tests.Unit/Services/ClassroomServiceTests/ClassroomServiceTests.Validation.Delete.cs
OtripleS.Web.Api/Models/Classrooms/Exceptions/InvalidClassroomInputException.cs
OtripleS.Web.Api/Models/Classrooms/Exceptions/LockedClassroomException.cs
OtripleS.Web.Api/Models/Classrooms/Exceptions/NotFoundClassroomException.cs
OtripleS.Web.Api/Services/Classrooms/ClassroomService.Exceptions.cs
OtripleS.Web.Api/Services/Classrooms/ClassroomService.Validations.cs
OtripleS.Web.Api/Services/Classrooms/ClassroomService.cs
OtripleS.Web.Api/Services/Classrooms/IClassroomService.cs

- Service - Delete
- Validations
- Exceptions

Classroom Service Delete

---

OtripleS.Web.Api.Tests.Unit/Services/ClassroomServiceTests/ClassroomServiceTests.Exceptions.RetrieveAll.cs
OtripleS.Web.Api.Tests.Unit/Services/ClassroomServiceTests/ClassroomServiceTests.Logic.cs
OtripleS.Web.Api.Tests.Unit/Services/ClassroomServiceTests/ClassroomServiceTests.Validations.RetrieveAll.cs
OtripleS.Web.Api.Tests.Unit/Services/ClassroomServiceTests/ClassroomServiceTests.cs
OtripleS.Web.Api/Migrations/20200720164344_AddClassroom.cs
OtripleS.Web.Api/Services/Classrooms/ClassroomService.Exceptions.cs
OtripleS.Web.Api/Services/Classrooms/ClassroomService.Validations.cs
OtripleS.Web.Api/Services/Classrooms/ClassroomService.cs
OtripleS.Web.Api/Services/Classrooms/IClassroomService.cs

- Service
- Validations
- Exceptions

Classroom Service Retrieve All

---

OtripleS.Web.Api.Tests.Unit/Services/ClassroomServiceTests/ClassroomServiceTests.Exceptions.Retrieve.cs
OtripleS.Web.Api.Tests.Unit/Services/ClassroomServiceTests/ClassroomServiceTests.Logic.cs
OtripleS.Web.Api.Tests.Unit/Services/ClassroomServiceTests/ClassroomServiceTests.Validations.Retrieve.cs
OtripleS.Web.Api/Controllers/ClassroomController.cs
OtripleS.Web.Api/Services/Classrooms/ClassroomService.Exceptions.cs
OtripleS.Web.Api/Services/Classrooms/ClassroomService.cs
OtripleS.Web.Api/Services/Classrooms/IClassroomService.cs

1. Completed the Retrieve classroom by id endpoint as it was not implemented and I needed this to finish one of my API endpoint tasks.
2. Completed the GetClassroom endpoint
3. Completed the DeleteClassroom endpoint.

Retrieve classroom by Id Service, Retrieve by Id end point and Delete end point

---

OtripleS.Web.Api.Tests.Unit/Services/StudentSemesterCourseServiceTests/StudentSemesterCourseServiceTests.Exceptions.Retrieve.cs
OtripleS.Web.Api.Tests.Unit/Services/StudentSemesterCourseServiceTests/StudentSemesterCourseServiceTests.Logic.cs
OtripleS.Web.Api.Tests.Unit/Services/StudentSemesterCourseServiceTests/StudentSemesterCourseServiceTests.Validations.Retrieve.cs
OtripleS.Web.Api.Tests.Unit/Services/StudentSemesterCourseServiceTests/StudentSemesterCourseServiceTests.cs
OtripleS.Web.Api/Services/StudentSemesterCourses/IStudentSemesterCourseService.cs
OtripleS.Web.Api/Services/StudentSemesterCourses/StudentSemesterCourseService.Exceptions.cs
OtripleS.Web.Api/Services/StudentSemesterCourses/StudentSemesterCourseService.Validations.cs
OtripleS.Web.Api/Services/StudentSemesterCourses/StudentSemesterCourseService.cs

StudentSemesterCourse get all service task

---

OtripleS.Web.Api/Controllers/StudentSemesterCoursesController.cs

@hassanhabib please check because I didn't know how to route this one. I did /api/studentsemestercourses/studentId/semesterCourseId

StudentSemesterCourse Controller Delete Endpoint

---

OtripleS.Web.Api.Tests.Unit/Services/GuardianServiceTests/GuardianServiceTests.Exceptions.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/GuardianServiceTests/GuardianServiceTests.Logic.cs
OtripleS.Web.Api.Tests.Unit/Services/GuardianServiceTests/GuardianServiceTests.Validations.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/GuardianServiceTests/GuardianServiceTests.cs
OtripleS.Web.Api/Models/Guardians/Exceptions/AlreadyExistsGuardianException.cs
OtripleS.Web.Api/Services/Guardians/GuardianService.Exceptions.cs
OtripleS.Web.Api/Services/Guardians/GuardianService.Validations.cs
OtripleS.Web.Api/Services/Guardians/GuardianService.cs
OtripleS.Web.Api/Services/Guardians/IGuardianService.cs
OtripleS.Web.Api/Startup.cs

Guardian Service Add function

---

OtripleS.Web.Api.Tests.Unit/Services/GuardianServiceTests/GuardianServiceTests.Exceptions.Delete.cs
OtripleS.Web.Api.Tests.Unit/Services/GuardianServiceTests/GuardianServiceTests.Logic.cs
OtripleS.Web.Api.Tests.Unit/Services/GuardianServiceTests/GuardianServiceTests.Validations.Delete.cs
OtripleS.Web.Api.Tests.Unit/Services/StudentServiceTests/StudentServiceTests.Validations.Delete.cs
OtripleS.Web.Api/Models/Guardians/Exceptions/LockedGuardianException.cs
OtripleS.Web.Api/Services/Guardians/GuardianService.Exceptions.cs
OtripleS.Web.Api/Services/Guardians/GuardianService.cs
OtripleS.Web.Api/Services/Guardians/IGuardianService.cs

Guardian Service Delete by Id function & Guardian Service Add function

---

OtripleS.Web.Api.Tests.Unit/Services/GuardianServiceTests/GuardianServiceTests.Exceptions.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/GuardianServiceTests/GuardianServiceTests.Exceptions.Delete.cs
OtripleS.Web.Api.Tests.Unit/Services/GuardianServiceTests/GuardianServiceTests.Validations.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/GuardianServiceTests/GuardianServiceTests.Validations.Delete.cs
OtripleS.Web.Api.Tests.Unit/Services/StudentGuardianServiceTests/StudentGuardianServiceTests.Exceptions.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/StudentGuardianServiceTests/StudentGuardianServiceTests.Logic.cs
OtripleS.Web.Api.Tests.Unit/Services/StudentGuardianServiceTests/StudentGuardianServiceTests.Validations.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/StudentGuardianServiceTests/StudentGuardianServiceTests.Validations.RetrieveAll.cs
OtripleS.Web.Api.Tests.Unit/Services/StudentGuardianServiceTests/StudentGuardianServiceTests.cs
OtripleS.Web.Api/Models/StudentGuardians/Exceptions/AlreadyExistsStudentGuardianException.cs
OtripleS.Web.Api/Services/StudentGuardians/IStudentGuardianService.cs
OtripleS.Web.Api/Services/StudentGuardians/StudentGuardianService.Exceptions.cs
OtripleS.Web.Api/Services/StudentGuardians/StudentGuardianService.Validations.cs
OtripleS.Web.Api/Services/StudentGuardians/StudentGuardianService.cs

StudentGuardian Service Add

---

OtripleS.Web.Api.Tests.Unit/Services/Contacts/ContactServiceTests.Exceptions.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/Contacts/ContactServiceTests.Logic.cs
OtripleS.Web.Api.Tests.Unit/Services/Contacts/ContactServiceTests.Validations.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/Contacts/ContactServiceTests.cs
OtripleS.Web.Api/Brokers/Storage/IStorageBroker.Contacts.cs
OtripleS.Web.Api/Brokers/Storage/StorageBroker.Contacts.cs
OtripleS.Web.Api/Migrations/20200922034313_AddContact.Designer.cs
OtripleS.Web.Api/Migrations/20200922034313_AddContact.cs
OtripleS.Web.Api/Models/Contacts/Contact.cs
OtripleS.Web.Api/Models/Contacts/ContactType.cs
OtripleS.Web.Api/Models/Contacts/Exceptions/AlreadyExistsContactException.cs
OtripleS.Web.Api/Models/Contacts/Exceptions/ContactDependencyException.cs
OtripleS.Web.Api/Models/Contacts/Exceptions/ContactServiceException.cs
OtripleS.Web.Api/Models/Contacts/Exceptions/ContactValidationException.cs
OtripleS.Web.Api/Models/Contacts/Exceptions/InvalidContactException.cs
OtripleS.Web.Api/Models/Contacts/Exceptions/NullContactException.cs
OtripleS.Web.Api/Services/Contacts/ContactService.Exceptions.cs
OtripleS.Web.Api/Services/Contacts/ContactService.Validations.cs
OtripleS.Web.Api/Services/Contacts/ContactService.cs
OtripleS.Web.Api/Services/Contacts/IContactService.cs
OtripleS.Web.Api/Startup.cs

Contact Service Add function

---

OtripleS.Web.Api.Tests.Unit/Services/Contacts/ContactServiceTests.Exceptions.Delete.cs
OtripleS.Web.Api.Tests.Unit/Services/Contacts/ContactServiceTests.Exceptions.Retrieve.cs
OtripleS.Web.Api.Tests.Unit/Services/Contacts/ContactServiceTests.Logic.cs
OtripleS.Web.Api.Tests.Unit/Services/Contacts/ContactServiceTests.Validations.Delete.cs
OtripleS.Web.Api.Tests.Unit/Services/Contacts/ContactServiceTests.Validations.Retrieve.cs
OtripleS.Web.Api/Controllers/ContactsController.cs
OtripleS.Web.Api/Services/Contacts/ContactService.Validations.cs
OtripleS.Web.Api/Services/Contacts/ContactService.cs
OtripleS.Web.Api/Services/Contacts/IContactService.cs

Contact Service Delete by Id

---

OtripleS.Web.Api.Tests.Acceptance/Brokers/OtripleSApiBroker.Contacts.cs
OtripleS.Web.Api.Tests.Acceptance/Contacts/ContactsApiTests.Logic.cs
OtripleS.Web.Api.Tests.Acceptance/Contacts/ContactsApiTests.cs

Completed Contacts Acceptance test

Contacts acceptance test

---

OtripleS.Web.Api.Tests.Unit/Services/TeacherContacts/TeacherContactServiceTests.Exceptions.RetrieveById.cs
OtripleS.Web.Api.Tests.Unit/Services/TeacherContacts/TeacherContactServiceTests.Logic.cs
OtripleS.Web.Api.Tests.Unit/Services/TeacherContacts/TeacherContactServiceTests.Validation.RetrieveById.cs
OtripleS.Web.Api/Controllers/StudentContactsController.cs
OtripleS.Web.Api/Services/TeacherContacts/ITeacherContactService.cs
OtripleS.Web.Api/Services/TeacherContacts/TeacherContactService.cs
OtripleS.Web.Api/Startup.cs

TeacherContact Service Retrieve by Id

---

OtripleS.Web.Api.Tests.Unit/Services/Exams/ExamServiceTests.Exceptions.RetrieveAll.cs
OtripleS.Web.Api.Tests.Unit/Services/Exams/ExamServiceTests.Logic.cs
OtripleS.Web.Api.Tests.Unit/Services/Exams/ExamServiceTests.Validations.RetrieveAll.cs
OtripleS.Web.Api.Tests.Unit/Services/Exams/ExamServiceTests.cs
OtripleS.Web.Api/Services/Exams/ExamService.Exceptions.cs
OtripleS.Web.Api/Services/Exams/ExamService.Validations.cs
OtripleS.Web.Api/Services/Exams/ExamService.cs

Exam Service Retrieve All

---

OtripleS.Web.Api.Tests.Unit/Services/Calendars/CalendarServiceTests.Exceptions.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/Calendars/CalendarServiceTests.Logic.cs
OtripleS.Web.Api.Tests.Unit/Services/Calendars/CalendarServiceTests.Validation.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/Calendars/CalendarServiceTests.cs
OtripleS.Web.Api/Models/Calendars/Exceptions/AlreadyExistsCalendarException.cs
OtripleS.Web.Api/Services/Calendars/CalendarService.Exceptions.cs
OtripleS.Web.Api/Services/Calendars/CalendarService.Validations.cs
OtripleS.Web.Api/Services/Calendars/CalendarService.cs
OtripleS.Web.Api/Services/Calendars/ICalendarService.cs

Calendar Service Add function

---

OtripleS.Web.Api.Tests.Acceptance/APIs/CalendarEntries/CalendarEntriesApiTest.cs
OtripleS.Web.Api.Tests.Acceptance/APIs/CalendarEntries/CalendarEntriesApiTest.logic.cs
OtripleS.Web.Api.Tests.Acceptance/Brokers/OtripleSApiBroker.CalenderEntries.cs
OtripleS.Web.Api.Tests.Acceptance/Models/CalendarEntries/CalendarEntry.cs

CalendarEntry Acceptance test(Get & Delete)

CalendarEntry Acceptance test(Get & Delete)

---

OtripleS.Web.Api.Tests.Unit/Services/Attachments/AttachmentServiceTests.Exceptions.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/Attachments/AttachmentServiceTests.Exceptions.RetrieveAll.cs
OtripleS.Web.Api.Tests.Unit/Services/Attachments/AttachmentServiceTests.Logic.cs
OtripleS.Web.Api.Tests.Unit/Services/Attachments/AttachmentServiceTests.Validations.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/Attachments/AttachmentServiceTests.Validations.RetrieveAll.cs
OtripleS.Web.Api.Tests.Unit/Services/Attachments/AttachmentServiceTests.cs
OtripleS.Web.Api/Models/Attachments/Exceptions/AlreadyExistsAttachmentException.cs
OtripleS.Web.Api/Models/Attachments/Exceptions/NullAttachmentException.cs
OtripleS.Web.Api/Services/Attchments/AttachmentService.Exceptions.cs
OtripleS.Web.Api/Services/Attchments/AttachmentService.Validations.cs
OtripleS.Web.Api/Services/Attchments/AttachmentService.cs
OtripleS.Web.Api/Services/Attchments/IAttachmentService.cs

Based on Branch AttachmentServiceAddFunction from @eriadhami

Retrieve all attachment service function

---

OtripleS.Web.Api.Tests.Unit/Services/StudentAttachments/StudentAttachmentServiceTests.Exceptions.Remove.cs
OtripleS.Web.Api/Controllers/StudentAttachmentsController.cs

- RetrieveAll
- RetrieveById
- Add
- RemoveById

StudentAttachment Controller

---

OtripleS.Web.Api.Tests.Unit/Services/StudentAttachments/StudentAttachmentServiceTests.Exceptions.Remove.cs

…sync -> PASS,
ShouldThrowDependencyExceptionOnRemoveWhenDbExceptionOccursAndLogItAsync -> PASS,
ShouldThrowDependencyExceptionOnRemoveWhenDbUpdateConcurrencyExceptionOccursAndLogItAsync -> PASS,
ShouldThrowServiceExceptionOnRemoveWhenExceptionOccursAndLogItAsync ->PASS

StudentAttachment Delete Exceptions

---

OtripleS.Web.Api.Tests.Unit/Services/GuardianAttachments/GuardianAttachmentServiceTests.cs
OtripleS.Web.Api/Controllers/GuardianAttachmentsController.cs
OtripleS.Web.Api/Services/GuardianAttachmets/GuardianAttachmentService.Exceptions.cs
OtripleS.Web.Api/Services/GuardianAttachmets/GuardianAttachmentService.Validations.cs
OtripleS.Web.Api/Services/GuardianAttachmets/GuardianAttachmentService.cs
OtripleS.Web.Api/Services/GuardianAttachmets/IGuardianAttachmentService.cs
OtripleS.Web.Api/Startup.cs

Guardian Attachment Controller

---

OtripleS.Web.Api/Controllers/TeacherAttachmentsController.cs

Teacher Attachment Controller API

---

OtripleS.Web.Api.Tests.Unit/Services/AssignmentAttachments/AssignmentAttachmentServiceTests.Exception.cs
OtripleS.Web.Api.Tests.Unit/Services/AssignmentAttachments/AssignmentAttachmentServiceTests.Exceptions.RetrieveById.cs
OtripleS.Web.Api/Models/AssignmentAttachments/Exceptions/AssignmentAttachmentDependencyValidationException.cs
OtripleS.Web.Api/Services/AssignmentAttachments/AssignmentAttachmentService.Exceptions.cs

CODE RUB:  DependencyValidation 

---

OtripleS.Web.Api.Tests.Unit/Services/Exams/ExamServiceTests.cs
OtripleS.Web.Api.Tests.Unit/Services/Fees/FeeServiceTests.cs
OtripleS.Web.Api/Brokers/Storage/IStorageBroker.ExamFees.cs
OtripleS.Web.Api/Brokers/Storage/StorageBroker.ExamFees.References.cs
OtripleS.Web.Api/Brokers/Storage/StorageBroker.ExamFees.cs
OtripleS.Web.Api/Brokers/Storage/StorageBroker.cs
OtripleS.Web.Api/Migrations/20210413113346_ExamFee.Designer.cs
OtripleS.Web.Api/Migrations/20210413113346_ExamFee.cs
OtripleS.Web.Api/Migrations/20210413121338_UpdatedExamFeeModel.Designer.cs
OtripleS.Web.Api/Migrations/20210413121338_UpdatedExamFeeModel.cs
OtripleS.Web.Api/Migrations/20210414055638_AddedExamFeeModelRelations.Designer.cs
OtripleS.Web.Api/Migrations/20210414055638_AddedExamFeeModelRelations.cs
OtripleS.Web.Api/Models/ExamFees/ExamFee.cs
OtripleS.Web.Api/Models/ExamFees/ExamFeeStatus.cs
OtripleS.Web.Api/Models/Exams/Exam.cs
OtripleS.Web.Api/Models/Fees/Fee.cs
OtripleS.Web.Api/Models/Users/User.cs

- ExamFee Model Setup & Migrations with EF Core
- ExamFee Broker Select By Id function
- ExamFee Broker Select All function 
- ExamFee Broker Insert function 
- ExamFee Broker Delete function 
- ExamFee Broker Update function

ExamFee entity model

---

OtripleS.Web.Api.Tests.Unit/Services/ExamFees/ExamFeeServiceTests.cs
OtripleS.Web.Api.Tests.Unit/Services/Students/StudentServiceTests.cs
OtripleS.Web.Api/Brokers/Storage/IStorageBroker.StudentExamFees.cs
OtripleS.Web.Api/Brokers/Storage/StorageBroker.StudentExamFees.References.cs
OtripleS.Web.Api/Brokers/Storage/StorageBroker.StudentExamFees.cs
OtripleS.Web.Api/Brokers/Storage/StorageBroker.cs
OtripleS.Web.Api/Migrations/20210420102351_StudentExamFeeModel.Designer.cs
OtripleS.Web.Api/Migrations/20210420102351_StudentExamFeeModel.cs
OtripleS.Web.Api/Models/ExamFees/ExamFee.cs
OtripleS.Web.Api/Models/StudentExamFees/StudentExamFee.cs
OtripleS.Web.Api/Models/StudentExamFees/StudentExamFeeStatus.cs
OtripleS.Web.Api/Models/Students/Student.cs
OtripleS.Web.Api/Models/Users/User.cs

Setup
StudentExamFee Model Setup & Migrations with EF Core 
Broker
StudentExamFee Broker Select By Id function 
StudentExamFee Broker Select All function 
StudentExamFee Broker Insert function 
StudentExamFee Broker Delete function 
StudentExamFee Broker Update function

Student Exam Fee Model

---

OtripleS.Web.Api.Tests.Acceptance/OtripleS.Web.Api.Tests.Acceptance.csproj
OtripleS.Web.Api.Tests.Unit/OtripleS.Web.Api.Tests.Unit.csproj
OtripleS.Web.Api/Controllers/AttachmentsController.cs
OtripleS.Web.Api/OtripleS.Web.Api.csproj

CODE RUB: Return 201 instead of 200 for Attachments Controller

---

OtripleS.Web.Api.Tests.Acceptance/OtripleS.Web.Api.Tests.Acceptance.csproj
OtripleS.Web.Api.Tests.Unit/OtripleS.Web.Api.Tests.Unit.csproj
OtripleS.Web.Api/Controllers/AssignmentsAttachmentsController.cs
OtripleS.Web.Api/OtripleS.Web.Api.csproj

CODE RUB: Return 201 instead of 200 for Assignments Attachments Controller

---

OtripleS.Web.Api.Tests.Acceptance/OtripleS.Web.Api.Tests.Acceptance.csproj
OtripleS.Web.Api.Tests.Unit/OtripleS.Web.Api.Tests.Unit.csproj
OtripleS.Web.Api/Controllers/AssignmentsController.cs
OtripleS.Web.Api/OtripleS.Web.Api.csproj

CODE RUB: Return 201 instead of 200 for Assignments Controller

---

OtripleS.Web.Api/Controllers/ClassroomsController.cs

CODE RUB: Return 201 instead of 200 for Classrooms Controller

---

OtripleS.Web.Api.Tests.Unit/Services/Attachments/AttachmentServiceTests.Validations.Add.cs
OtripleS.Web.Api/Models/Attachments/Attachment.cs
OtripleS.Web.Api/Services/Attachments/AttachmentService.Validations.cs

In the Attachment model:
ContectType -> ContentType

CODE RUB: fixed typo

---

OtripleS.Web.Api/Controllers/UsersController.cs

CODE RUB: Return 201 instead of 200 for Users Controller

---

OtripleS.Web.Api/Controllers/UserContactsController.cs

CODE RUB: Return 201 instead of 200 for User Contacts Controller

---

OtripleS.Web.Api/Controllers/TeachersController.cs

CODE RUB: Return 201 instead of 200 for Teachers Controller

---

OtripleS.Web.Api/Controllers/TeacherContactsController.cs

CODE RUB: Return 201 instead of 200 for Teacher Contacts Controller

---

OtripleS.Web.Api/Controllers/TeacherAttachmentsController.cs

CODE RUB: Return 201 instead of 200 for Teacher Attachments Controller

---

OtripleS.Web.Api/Controllers/StudentSemesterCoursesController.cs

CODE RUB: Return 201 instead of 200 for Student Semester Courses Controller

---

OtripleS.Web.Api/Controllers/StudentsController.cs

CODE RUB: Return 201 instead of 200 for Students Controller

---

OtripleS.Web.Api/Controllers/StudentRegistrationsController.cs

CODE RUB: Return 201 instead of 200 for Student Registrations Controller

---

OtripleS.Web.Api/Controllers/StudentGuardiansController.cs

CODE RUB: Return 201 instead of 200 for Student Guardians Controller

---

OtripleS.Web.Api/Controllers/StudentExamsController.cs

CODE RUB: Return 201 instead of 200 for Student Exams Controller

---

OtripleS.Web.Api/Controllers/StudentContactsController.cs

CODE RUB: Return 201 instead of 200 for Student Contacts Controller

---

OtripleS.Web.Api/Controllers/StudentAttachmentsController.cs

CODE RUB: Return 201 instead of 200 for Student Attachments Controller

---

OtripleS.Web.Api/Controllers/SemesterCoursesController.cs

CODE RUB: Return 201 instead of 200 for Semester Courses Controller

---

OtripleS.Web.Api/Controllers/RegistrationsController.cs

CODE RUB: Return 201 instead of 200 for Registrations Controller

---

OtripleS.Web.Api/Controllers/GuardiansController.cs

CODE RUB: Return 201 instead of 200 for Guardians Controller

---

OtripleS.Web.Api/Controllers/GuardianAttachmentsController.cs

CODE RUB: Return 201 instead of 200 for Guardian Attachments Controller

---

OtripleS.Web.Api/Controllers/GuardianContactsController.cs

CODE RUB: Return 201 instead of 200 for Guardian Contacts Controller

---

OtripleS.Web.Api/Controllers/FeesController.cs

CODE RUB: Return 201 instead of 200 for Fees Controller

---

OtripleS.Web.Api/Controllers/ExamsController.cs

CODE RUB: Return 201 instead of 200 for Exams Controller

---

OtripleS.Web.Api/Controllers/ExamsAttachmentsController.cs

CODE RUB: Return 201 instead of 200 for Exams Attachments Controller

---

OtripleS.Web.Api/Controllers/CoursesController.cs

CODE RUB: Return 201 instead of 200 for Courses Controller

---

OtripleS.Web.Api/Controllers/CoursesAttachmentsController.cs
OtripleS.Web.Api/Models/CoursesAttachments/CourseAttachment.cs

Also took out empty line in CourseAttachments model.

CODE RUB: Return 201 instead of 200 for Courses Attachments Controller

---

OtripleS.Web.Api/Controllers/ContactsController.cs

CODE RUB: Return 201 instead of 200 for Contacts Controller

---

OtripleS.Web.Api/Controllers/CalendarsController.cs

CODE RUB: Return 201 instead of 200 for Calendars Controller

---

OtripleS.Web.Api/Controllers/CalendarEntriesController.cs

CODE RUB: Return 201 instead of 200 for Calendar Entries Controller

---

OtripleS.Web.Api/Controllers/CalendarEntriesAttachmentsController.cs

CODE RUB: Return 201 instead of 200 for Calendar Entries Attachments Controller

---

OtripleS.Web.Api/Controllers/StudentExamFeesController.cs

CODE RUB: Return 201 instead of 200 for Student Exam Fees Controller

---

OtripleS.Web.Api/Brokers/Storages/StorageBroker.ExamFees.cs
OtripleS.Web.Api/Brokers/UserManagement/UserManagerBroker.cs
OtripleS.Web.Api/Controllers/ExamFeesController.cs

CODE RUB: Return 201 instead of 200 for Exam Fees Controller

---

OtripleS.Web.Api/Brokers/Storages/IStorageBroker.AssignmentAttachments.cs
OtripleS.Web.Api/Brokers/Storages/IStorageBroker.CalendarEntryAttachments.cs
OtripleS.Web.Api/Brokers/Storages/IStorageBroker.Contacts.cs
OtripleS.Web.Api/Brokers/Storages/IStorageBroker.CourseAttachments.cs
OtripleS.Web.Api/Brokers/Storages/IStorageBroker.ExamAttachments.cs
OtripleS.Web.Api/Brokers/Storages/IStorageBroker.ExamFees.cs
OtripleS.Web.Api/Brokers/Storages/IStorageBroker.Fees.cs
OtripleS.Web.Api/Brokers/Storages/IStorageBroker.GuardianAttachments.cs
OtripleS.Web.Api/Brokers/Storages/IStorageBroker.GuardianContacts.cs
OtripleS.Web.Api/Brokers/Storages/IStorageBroker.Registrations.cs
OtripleS.Web.Api/Brokers/Storages/IStorageBroker.StudentAttachments.cs
OtripleS.Web.Api/Brokers/Storages/IStorageBroker.StudentContacts.cs
OtripleS.Web.Api/Brokers/Storages/IStorageBroker.StudentExamFees.cs
OtripleS.Web.Api/Brokers/Storages/IStorageBroker.StudentExams.cs
OtripleS.Web.Api/Brokers/Storages/IStorageBroker.StudentGuardians.cs
OtripleS.Web.Api/Brokers/Storages/IStorageBroker.StudentSemesterCourses.cs
OtripleS.Web.Api/Brokers/Storages/IStorageBroker.Students.cs
OtripleS.Web.Api/Brokers/Storages/IStorageBroker.TeacherAttachments.cs
OtripleS.Web.Api/Brokers/Storages/IStorageBroker.TeacherContacts.cs
OtripleS.Web.Api/Brokers/Storages/IStorageBroker.UserContacts.cs

Cleaned up Storage Broker interface definitions and removed explicit "public" access modifier

CODE RUB: Storage Broker Interface Definition Cleanup

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/CourseAttachments/CourseAttachmentServiceTests.Validations.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/CourseAttachments/CourseAttachmentServiceTests.Validations.Remove.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/CourseAttachments/CourseAttachmentServiceTests.Validations.RetrieveById.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/CourseAttachments/CourseAttachmentServiceTests.cs
OtripleS.Web.Api/Models/CoursesAttachments/Exceptions/InvalidCourseAttachmentException.cs
OtripleS.Web.Api/Services/Foundations/CourseAttachments/CourseAttachmentService.Validations.cs
OtripleS.Web.Api/Services/Foundations/CourseAttachments/CourseAttachmentService.cs

- Add
- Remove
- Retrieve By Ids
#437

CODE RUB: Upgrade Course Attachments to New Validation Standard

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/Contacts/ContactServiceTests.Validations.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/Contacts/ContactServiceTests.Validations.Modify.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/Contacts/ContactServiceTests.cs
OtripleS.Web.Api/Controllers/ContactsController.cs
OtripleS.Web.Api/Models/Contacts/Exceptions/InvalidContactException.cs
OtripleS.Web.Api/Services/Foundations/Contacts/ContactService.Validations.cs

#437 Foundations contacts validation standard changes

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/TeacherAttachments/TeacherAttachmentServiceTests.cs

#628 can be closed upon the successful merge of this PR.

CODE RUB: Teacher Attachment Filler method order

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/AssignmentAttachments/AssignmentAttachmentServiceTests.cs

CODE RUB: Assignment Attachment Filler method order

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/CourseAttachments/CourseAttachmentServiceTests.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentGuardians/StudentGuardianServiceTests.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentSemesterCourses/StudentSemesterCourseServiceTests.cs

Closes #[626](https://github.com/hassanhabib/OtripleS/issues/626)

CODE RUB: Change Student Guardian Filler method order

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentExamFees/StudentExamFeeServiceTests.cs

Closes #[625](https://github.com/hassanhabib/OtripleS/issues/625)

CODE RUB: Student Exam Fee Filler method order

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentAttachments/StudentAttachmentServiceTests.cs

Closes #[623](https://github.com/hassanhabib/OtripleS/issues/623)

CODE RUB: Changed Student Attachment Filler method order.

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/Fees/FeeServiceTests.cs

CODE RUB: Changed Fee Filler method order

---

OtripleS.Web.Api.Tests.Acceptance/APIs/Attendances/AttendancesApiTests.cs
OtripleS.Web.Api.Tests.Acceptance/APIs/Courses/CoursesApiTests.cs
OtripleS.Web.Api.Tests.Acceptance/APIs/CoursesAttachments/CourseAttachmentsApiTests.cs
OtripleS.Web.Api.Tests.Acceptance/APIs/ExamFees/ExamFeesApiTests.cs
OtripleS.Web.Api.Tests.Acceptance/APIs/Exams/ExamsApiTests.cs
OtripleS.Web.Api.Tests.Acceptance/APIs/ExamsAttachments/ExamAttachmentsApiTests.cs
OtripleS.Web.Api.Tests.Acceptance/APIs/SemesterCourses/SemesterCoursesApiTests.cs
OtripleS.Web.Api.Tests.Acceptance/APIs/StudentExamFees/StudentExamFeesApiTests.cs
OtripleS.Web.Api.Tests.Acceptance/APIs/StudentExams/StudentExamsApiTests.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/Courses/CourseServiceTests.Validations.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/Courses/CourseServiceTests.cs
OtripleS.Web.Api/Services/Foundations/Courses/CourseService.Validations.cs

CODE RUB: Course Status Enum Validation

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/GuardianContacts/GuardianContactServiceTests.cs

Closes #[620](https://github.com/hassanhabib/OtripleS/issues/620)

CODE RUB: Changed Guardian Contact Filler method order

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/SemesterCourses/SemesterCourseServiceTests.cs

Closes #[622](https://github.com/hassanhabib/OtripleS/issues/622)

CODE RUB: Change Semester Course Filler method order

---

OtripleS.Web.Api.Tests.Acceptance/APIs/Attendances/AttendancesApiTests.cs
OtripleS.Web.Api.Tests.Acceptance/APIs/Classrooms/ClassroomsApiTests.cs
OtripleS.Web.Api.Tests.Acceptance/APIs/ExamFees/ExamFeesApiTests.cs
OtripleS.Web.Api.Tests.Acceptance/APIs/Exams/ExamsApiTests.cs
OtripleS.Web.Api.Tests.Acceptance/APIs/ExamsAttachments/ExamAttachmentsApiTests.cs
OtripleS.Web.Api.Tests.Acceptance/APIs/SemesterCourses/SemesterCoursesApiTests.cs
OtripleS.Web.Api.Tests.Acceptance/APIs/StudentExamFees/StudentExamFeesApiTests.cs
OtripleS.Web.Api.Tests.Acceptance/APIs/StudentExams/StudentExamsApiTests.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/Classrooms/ClassroomServiceTests.Validations.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/Classrooms/ClassroomServiceTests.cs
OtripleS.Web.Api/Services/Foundations/Classrooms/ClassroomService.Validations.cs

CODE RUB: Classroom Status Enum Validation

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/Calendars/CalendarServiceTests.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/GuardianAttachments/GuardianAttachmentServiceTests.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/SemesterCourses/SemesterCourseServiceTests.cs

Closes #[606](https://github.com/hassanhabib/OtripleS/issues/606)

CODE RUB: calendar filler method order

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/Attendances/AttendanceServiceTests.cs

CODE RUB: Attendances Filler method order

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/Assignments/AssignmentServiceTests.cs

CODE RUB: Fix AssignmentServiceTests SameExceptionAs method

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/Calendars/CalendarServiceTests.cs

CODERUB: Fix CalendarServiceTests SameExceptionAs Method

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/Contacts/ContactServiceTests.cs

closes [#579](https://github.com/hassanhabib/OtripleS/issues/579)

CODE RUB: Contact SameExceptionAs correction

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exceptions.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exceptions.Modify.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exceptions.Remove.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exceptions.RetrieveAll.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exceptions.RetrieveById.cs
OtripleS.Web.Api/Models/Users/Exceptions/FailedUserStorageException.cs
OtripleS.Web.Api/Services/Foundations/Users/UserService.Exceptions.cs

Closes #[553](https://github.com/hassanhabib/OtripleS/issues/553)

CODE RUB: Localize Users Dependency Exception

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/GuardianAttachments/GuardianAttachmentServiceTests.cs

CODE RUB: Change Guardian Attach Filler method

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/Exams/ExamServiceTests.cs

CODE RUB: Exam SameExceptionAs correction

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/Classrooms/ClassroomServiceTests.cs

CODE RUB: Classroom SameExceptionAs correction

---

OtripleS.Web.Api/Brokers/Storages/StorageBroker.AssignmentAttachments.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.CalendarEntries.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.CalendarEntryAttachments.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.CourseAttachments.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.ExamAttachments.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.ExamFees.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.Exams.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.Fees.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.GuardianAttachments.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.GuardianContacts.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.Registrations.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.SemesterCourses.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.StudentAttachments.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.StudentContacts.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.StudentExamFees.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.StudentExams.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.StudentGuardians.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.StudentRegistrations.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.StudentSemesterCourses.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.TeacherAttachments.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.TeacherContacts.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.UserContacts.References.cs
OtripleS.Web.Api/Brokers/Storages/StorageBroker.cs

CODE RUB: Change methodname from Add to Set

CODE RUB: Change methodname from Add to Set

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/Contacts/ContactServiceTests.Exceptions.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/Contacts/ContactServiceTests.Exceptions.Modify.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/Contacts/ContactServiceTests.Exceptions.Remove.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/Contacts/ContactServiceTests.Exceptions.Retrieve.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/Contacts/ContactServiceTests.cs
OtripleS.Web.Api/Models/Contacts/Exceptions/ContactDependencyException.cs
OtripleS.Web.Api/Models/Contacts/Exceptions/FailedContactStorageException.cs
OtripleS.Web.Api/Services/Foundations/Contacts/ContactService.Exceptions.cs

CODE RUB: Localize Dependency Exceptions - Contacts

---

OtripleS.Web.Api/Services/Foundations/TeacherAttachments/TeacherAttachmentService.cs

CODE RUB: Replace Storage Teacher Attachment with Maybe Storage Attachment

---

OtripleS.Web.Api/OtripleS.Web.Api.csproj
OtripleS.Web.Api/Properties/launchSettings.json
OtripleS.Web.Api/Startup.cs

CONFIG: Add Swagger

---

OtripleS.Api.Infrastructure.Provision/Brokers/Clouds/CloudBroker.Plans.cs
OtripleS.Api.Infrastructure.Provision/Brokers/Clouds/CloudBroker.ResourceGroups.cs
OtripleS.Api.Infrastructure.Provision/Brokers/Clouds/CloudBroker.Storages.cs
OtripleS.Api.Infrastructure.Provision/Brokers/Clouds/CloudBroker.WebApps.cs
OtripleS.Api.Infrastructure.Provision/Brokers/Clouds/CloudBroker.cs
OtripleS.Api.Infrastructure.Provision/Brokers/Clouds/ICloudBroker.Plans.cs
OtripleS.Api.Infrastructure.Provision/Brokers/Clouds/ICloudBroker.ResourceGroups.cs
OtripleS.Api.Infrastructure.Provision/Brokers/Clouds/ICloudBroker.Storages.cs
OtripleS.Api.Infrastructure.Provision/Brokers/Clouds/ICloudBroker.WebApps.cs
OtripleS.Api.Infrastructure.Provision/Brokers/Clouds/ICloudBroker.cs
OtripleS.Api.Infrastructure.Provision/Brokers/Configurations/ConfigurationBroker.cs
OtripleS.Api.Infrastructure.Provision/Brokers/Configurations/IConfigurationBroker.cs
OtripleS.Api.Infrastructure.Provision/Brokers/Loggings/ILoggingBroker.cs
OtripleS.Api.Infrastructure.Provision/Brokers/Loggings/LoggingBroker.cs
OtripleS.Api.Infrastructure.Provision/Models/Configurations/CloudAction.cs
OtripleS.Api.Infrastructure.Provision/Models/Configurations/CloudManagementConfiguration.cs
OtripleS.Api.Infrastructure.Provision/Models/Configurations/CloudManagementsConfiguration.cs
OtripleS.Api.Infrastructure.Provision/Models/Storages/SqlDatabase.cs
OtripleS.Api.Infrastructure.Provision/Models/Storages/SqlDatabaseAccess.cs
OtripleS.Api.Infrastructure.Provision/OtripleS.Web.Api.Infrastructure.Provision.csproj
OtripleS.Api.Infrastructure.Provision/Program.cs
OtripleS.Api.Infrastructure.Provision/Services/Foundations/CloudManagements/CloudManagementService.cs
OtripleS.Api.Infrastructure.Provision/Services/Foundations/CloudManagements/ICloudManagementService.cs
OtripleS.Api.Infrastructure.Provision/Services/Processings/CloudManagements/CloudManagementProcessingService.cs
OtripleS.Api.Infrastructure.Provision/Services/Processings/CloudManagements/ICloudManagementProcessingService.cs
OtripleS.Api.Infrastructure.Provision/appSettings.json
OtripleS.sln

Closes #[854](https://github.com/hassanhabib/OtripleS/issues/854)
I may have made a slight mistake on the first 3 commit in terms of naming they should BROKER instead of PROVISION.

PROVISION: Initialize Provisioning for ASP.NET Core API

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/UserContacts/UserContactServiceTests.Exceptions.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/UserContacts/UserContactServiceTests.Exceptions.Remove.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/UserContacts/UserContactServiceTests.Exceptions.RetrieveAll.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/UserContacts/UserContactServiceTests.Exceptions.RetrieveById.cs
OtripleS.Web.Api/Models/UserContacts/Exceptions/FailedUserContactStorageException.cs
OtripleS.Web.Api/Services/Foundations/UserContacts/UserContactService.Exceptions.cs

Closes #[552](https://github.com/hassanhabib/OtripleS/issues/552)

CODE RUB: Localize Dependency Exceptions User Contacts

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/Classrooms/ClassroomServiceTests.Exceptions.Add.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/Classrooms/ClassroomServiceTests.Exceptions.Modify.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/Classrooms/ClassroomServiceTests.Exceptions.Remove.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/Classrooms/ClassroomServiceTests.Exceptions.Retrieve.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/Classrooms/ClassroomServiceTests.Exceptions.RetrieveAll.cs
OtripleS.Web.Api/Models/Classrooms/Exceptions/ClassroomDependencyException.cs
OtripleS.Web.Api/Models/Classrooms/Exceptions/ClassroomDependencyValidationException.cs
OtripleS.Web.Api/Models/Classrooms/Exceptions/FailedClassroomStorageException.cs
OtripleS.Web.Api/Models/Classrooms/Exceptions/LockedClassroomException.cs
OtripleS.Web.Api/OtripleS.Web.Api.csproj
OtripleS.Web.Api/Services/Foundations/Classrooms/ClassroomService.Exceptions.cs

CODE RUB: Localize Dependency Exceptions - Classrooms

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/UserContacts/UserContactServiceTests.Validations.Add.cs

The changes I made were unintentionally commited to master branch from which I got checkout out my branch. I hope this isn't going to cause a problem. I am sorry for that and try to be more careful next time...

CODE RUB: Refactor the code to be simple

---

OtripleS.Web.Api/Services/Foundations/StudentGuardians/StudentGuardianService.Validations.cs
OtripleS.Web.Api/Services/Foundations/Students/StudentService.Validations.cs
OtripleS.Web.Api/Services/Foundations/Teachers/TeacherService.Validations.cs

Use is null instead of default

CODE RUB: Use Is Not Null Instead of Default

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/Calendars/CalendarServiceTests.Exceptions.RetriveById.cs

CODE RUB: Replace Input variables in Exception Tests with Some Variable

CODE RUB: Replace Input variables in Exception Tests with Some Variable

---

.github/workflows/dotnet.yml
OtripleS.Web.Api.Infrastructure.Build/Program.cs

New release of `.NET` is out which is `6.0.101`

CONFIG: Update .NET Version to 6.0.101

---

.github/workflows/dotnet.yml
OtripleS.Web.Api.Infrastructure.Build/OtripleS.Web.Api.Infrastructure.Build.csproj
OtripleS.Web.Api.Infrastructure.Build/Program.cs

Reverts hassanhabib/OtripleS#1368

CODE RUB: Testing Timeout

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/Classrooms/ClassroomServiceTests.Validations.Retrieve.cs

: Classrooms Validations VerifyDependencies

MINOR FIX: Classrooms Validations VerifyDependencies

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/Assignments/AssignmentServiceTests.Logic.Remove.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/Assignments/AssignmentServiceTests.Logic.cs

CODE RUB : Separate logic test for Remove assignments

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentGuardians/StudentGuardianServiceTests.Logic.RegisterAll.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentGuardians/StudentGuardianServiceTests.Logic.cs

CODE RUB: SEPARATE LOGIC TEST FOR RETRIEVE ALL OPERATION - Student Guardians

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentRegistrations/StudentRegistrationServiceTests.Logic.RetrieveAll.cs
OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentRegistrations/StudentRegistrationServiceTests.Logic.cs

CODE RUB: SEPARATE LOGIC TEST FOR RETRIEVE ALL OPERATION -Student Registration

---

OtripleS.Web.Api/Services/Foundations/Contacts/ContactService.Validations.cs

CODE RUB: Remove Extra Line 

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exceptions.Add.cs

CODE RUB: User Add - SqlException

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/AssignmentAttachments/AssignmentAttachmentServiceTests.Exceptions.Add.cs

CODE RUB : AssignmentAttachments - Add Sql Exception

---

OtripleS.Web.Api/Services/Foundations/AssignmentAttachments/AssignmentAttachmentService.Validations.cs

CODE RUB: Indent Params

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/TeacherAttachments/TeacherAttachmentServiceTests.Exceptions.RetrievById.cs

CODERUB : Teacher Attachments - Retrieve By Id - Db Update - Exception

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentSemesterCourses/StudentSemesterCourseServiceTests.Exceptions.Modify.cs

CODE RUB : StudentSemesterCourse - Modify - Db Update Concurrency Exception

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentSemesterCourses/StudentSemesterCourseServiceTests.Exceptions.RetrieveById.cs

CODE RUB: StudentSemesterCourse-RetrieveById-DbConcurrency-InputToSome

---

OtripleS.Web.Api.Tests.Unit/Services/Foundations/GuardianContacts/GuardianContactServiceTests.Exceptions.RetrieveById.cs

CODE RUB: GuardianContacts-RetrieveById-SqlException-InputToSome

---

README.md

Also removes degraded badges BCH and Teams

Documentations: Add Readme Badge Versioning

---

OtripleS.Web.Api/Services/Foundations/Students/StudentService.Validations.cs

Setting to same level exceeds 120char max rule
Closes: #1968

CODE RUB: Rule Parameter Fix Indentations
